version: "3"
services:
  app:
    container_name: mern
    restart: always
    build: .
    ports: 
      - "4000:4000"
    links:
      - mongo
  mongo:
    container_name: mongo-database
    image: mongo
    ports:
      - "27017:27017" 
  nginx:
      restart: always
      build: .
      ports:
          - "80:80" 
